<a href="https://colab.research.google.com/github/Kaushal-Top5699/tensorflow_05/blob/main/tensorflow_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
# Changing dataType of tensors
A = tf.constant([[1, 2, 3],
                [4, 5, 6]])
A

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [3]:
B = tf.constant([[1.1, 2.2, 3.3],
                 [4.4, 5.5, 6.6]])
B

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.1, 2.2, 3.3],
       [4.4, 5.5, 6.6]], dtype=float32)>

In [4]:
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1.1, 2.2, 3.3],
       [4.4, 5.5, 6.6]], dtype=float16)>

In [5]:
# Change from int32 to float32
E = tf.cast(A, dtype=tf.float32)
E

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [6]:
# Change from int32 to float16
F = tf.cast(A, dtype=tf.float16)
F

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

# **Aggregating Tensor**

In [7]:
tensor_1 = tf.constant([-1, -2])
tensor_1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2], dtype=int32)>

In [8]:
# Getting absolute value
tf.abs(tensor_1)
# Takes the negatives and turns them into positive

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

### **Forms of aggregation**

1) Minima

2) Maxima

3) Mean

4) Sum

In [9]:
# Getting maximum/minimum tensor
tensor_2 = tf.constant([[11, 2, 3],
                        [45, 50, 6]])

tensor_3 = tf.constant([[7, 8, 9],
                        [10, 111, 12]])

tensor_2, tensor_3

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[11,  2,  3],
        [45, 50,  6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[  7,   8,   9],
        [ 10, 111,  12]], dtype=int32)>)

In [10]:
# tf.maximum()
tf.maximum(tensor_2, tensor_3)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 11,   8,   9],
       [ 45, 111,  12]], dtype=int32)>

In [11]:
# Getting minimum tensor
tf.minimum(tensor_2, tensor_3)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  2,  3],
       [10, 50,  6]], dtype=int32)>

In [12]:
# Getting mean of tensor
tf.reduce_mean(tensor_3)

<tf.Tensor: shape=(), dtype=int32, numpy=26>

In [13]:
# Getting sum of tensor
tf.reduce_sum(tensor_3)

<tf.Tensor: shape=(), dtype=int32, numpy=157>

In [32]:
import numpy as np
tensor_4 = tf.constant(np.random.randint(0, 100, size = 50))
tensor_4

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([95, 30, 28, 79, 40,  5, 77, 15, 73, 80, 18, 52, 46, 14, 36, 88, 99,
       86, 45, 23, 86, 27, 78, 66, 87, 95, 25, 99, 50, 83, 71, 14, 75, 93,
       23, 46, 14, 48, 83, 15, 16, 18, 93, 39, 69,  9, 66, 94, 56, 37])>

In [33]:
tf.reduce_sum(tensor_4), tf.reduce_mean(tensor_4), tf.size(tensor_4), tf.shape(tensor_4), tensor_4.ndim

(<tf.Tensor: shape=(), dtype=int64, numpy=2704>,
 <tf.Tensor: shape=(), dtype=int64, numpy=54>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([50], dtype=int32)>,
 1)

In [34]:
# Finding minimum value in a tensor
tf.reduce_min(tensor_4)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [35]:
# Finding a maximum value in a tensor
tf.reduce_max(tensor_4)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

**We need to cast it to float either float16 or float32 in order to get the standard deviation!!**

In [44]:
tensor_5 = tf.cast(tensor_4, dtype=tf.float16)
tensor_5

<tf.Tensor: shape=(50,), dtype=float16, numpy=
array([95., 30., 28., 79., 40.,  5., 77., 15., 73., 80., 18., 52., 46.,
       14., 36., 88., 99., 86., 45., 23., 86., 27., 78., 66., 87., 95.,
       25., 99., 50., 83., 71., 14., 75., 93., 23., 46., 14., 48., 83.,
       15., 16., 18., 93., 39., 69.,  9., 66., 94., 56., 37.],
      dtype=float16)>

### **To get variance and stand deviation we need to import tensorflow_probability lib.**

In [38]:
import tensorflow_probability as tfp

In [39]:
# Getting the variance
tfp.stats.variance(tensor_5)

<tf.Tensor: shape=(), dtype=float16, numpy=887.5>

In [52]:
# We can also find variance in another way with using tensorflow_probability lib
tf.math.reduce_variance(tensor_5)

<tf.Tensor: shape=(), dtype=float16, numpy=887.5>

**🫵🏼 Remember to get Standard Deviation of a tensor it must be real or complex collection of numbers. Therefore, convert it to float either flot16 or float32.**

In [40]:
# Getting the standard deviation
tf.math.reduce_std(tensor_5)

<tf.Tensor: shape=(), dtype=float16, numpy=29.8>

## **Positional Maximum and Minimum**

In [43]:
# Returns the index of maximum value within our tensor
tf.math.argmax(tensor_5)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [46]:
# We can get that max value using the returned index
tensor_5[tf.math.argmax(tensor_5)]

<tf.Tensor: shape=(), dtype=float16, numpy=99.0>

In [47]:
# Getting the minimum value index
tf.math.argmin(tensor_5)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [50]:
# Fetching minimum value from tensor_5 using returned min index
tensor_5[tf.math.argmin(tensor_5)]

<tf.Tensor: shape=(), dtype=float16, numpy=5.0>

In [51]:
# Verify by observing below tensor
tensor_5

<tf.Tensor: shape=(50,), dtype=float16, numpy=
array([95., 30., 28., 79., 40.,  5., 77., 15., 73., 80., 18., 52., 46.,
       14., 36., 88., 99., 86., 45., 23., 86., 27., 78., 66., 87., 95.,
       25., 99., 50., 83., 71., 14., 75., 93., 23., 46., 14., 48., 83.,
       15., 16., 18., 93., 39., 69.,  9., 66., 94., 56., 37.],
      dtype=float16)>

In [56]:
# Another way of creating a random tensor without using numpy.
tensor_6 = tf.random.uniform(shape = [50])
tensor_6

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.5877372 , 0.4624158 , 0.9785259 , 0.07478976, 0.8760371 ,
       0.77205265, 0.3573084 , 0.90385723, 0.5055258 , 0.42717922,
       0.637331  , 0.158144  , 0.78713596, 0.8428781 , 0.30233443,
       0.9859817 , 0.7895652 , 0.31250715, 0.20265949, 0.43143153,
       0.52685726, 0.50693655, 0.04036963, 0.38694727, 0.21692872,
       0.36567688, 0.49148762, 0.32402945, 0.96995926, 0.9001161 ,
       0.32840407, 0.7690536 , 0.8258953 , 0.68117046, 0.8404051 ,
       0.832677  , 0.18434167, 0.8288015 , 0.0642364 , 0.21103954,
       0.16556144, 0.28087544, 0.7040119 , 0.42915404, 0.623458  ,
       0.38058603, 0.47649276, 0.35521924, 0.7885771 , 0.73870707],
      dtype=float32)>

In [59]:
# Again we can perform the above operations
print(f'Index of max value = {tf.math.argmax(tensor_6)}') 
print(f'Value at that index = {tensor_6[tf.math.argmax(tensor_6)]}')
print(f'Index of min value = {tf.math.argmin(tensor_6)}') 
print(f'Value at that index = {tensor_6[tf.math.argmin(tensor_6)]}')

Index of max value = 15
Value at that index = 0.9859817028045654
Index of min value = 22
Value at that index = 0.040369629859924316
